roles = [
    "Admin",
    "General"
]

users = [
    {"email": "maria@gmail.com",
     "name": "Maria Perez",
     "password": "123456789",
     "role_id": 2},
]

categories = [
    {"name": "History"},
    {"name": "Science Fiction"},
    {"name": "Romance"},
    {"name": "Poetry"},
    {"name": "Children"}
]

authors = [
    {"name": "Stephen King"},
    {"name": "J.K. Rowling"},
    {"name": "Colleen Hoover"},
    {"name": "Neil Gaiman"},
    {"name": "Rupi Kaur"},
    {"name": "Siddhartha Mukherjee"},
    {"name": "Erik Larson"},
    {"name": "Dr. Seuss"},
    {"name": "Agatha Christie"},
    {"name": "Harper Lee"},
]

products = [
    # Category: History (ID 1)
    {
        "name": "The Splendid and the Vile",
        "price": 18.99,
        "image_url": "https://www.portland5.com/sites/default/files/2021/10/22/Larson-The-Splendid-and-the-Vile-Book-Cover-200w.jpg",
        "is_featured": True,
        "description": "A thrilling narrative of Winston Churchill and his inner circle during the Blitz by Erik Larson.",
        "detail_images": ['https://m.media-amazon.com/images/I/51bpXBnreyL._SX679_.jpg'],
        "rating": 5,
        "product_stock": 30,
        "category_id": 1,
        "author_ids": [7],
    },
    {
        "name": "The Emperor of All Maladies",
        "price": 22.50,
        "image_url": "https://m.media-amazon.com/images/I/91usu4BCD2L._SY466_.jpg",
        "is_featured": False,
        "description": "A biography of cancer told through its history, from its first documented appearances to the latest treatments by Siddhartha Mukherjee.",
        "detail_images": ['https://m.media-amazon.com/images/I/81CvPD2a+uL._SY466_.jpg'],
        "rating": 5,
        "product_stock": 25,
        "category_id": 1,
        "author_ids": [6],
    },
    {
        "name": "To Kill a Mockingbird",
        "price": 11.99,
        "image_url": "https://m.media-amazon.com/images/I/61lo4E4lHfL._SY342_.jpg",
        "is_featured": True,
        "description": "A classic of modern American literature, exploring issues of race and justice in the South by Harper Lee.",
        "detail_images": ['https://m.media-amazon.com/images/I/51MUsai+UdL._SY342_.jpg'],
        "rating": 5,
        "product_stock": 40,
        "category_id": 1,
        "author_ids": [10],
    },
    {
        "name": "In Cold Blood",
        "price": 15.75,
        "image_url": "https://m.media-amazon.com/images/I/31owxaciJtL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": False,
        "description": "A non-fiction novel detailing the murders of the Clutter family in Kansas by Truman Capote.",
        "detail_images": ['https://m.media-amazon.com/images/I/61plkkkkKyL._SY342_.jpg'],
        "rating": 4,
        "product_stock": 20,
        "category_id": 1,
        "author_ids": [10],
    },

    # Category: Science Fiction (ID 2)
    {
        "name": "American Gods",
        "price": 13.50,
        "image_url": "https://m.media-amazon.com/images/I/41Zdb78xM2L._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": True,
        "description": "A fantasy novel by Neil Gaiman about the Old Gods and New Gods of America.",
        "detail_images": ['https://en.wikipedia.org/wiki/American_Gods#/media/File:American_gods.jpg'],
        "rating": 5,
        "product_stock": 35,
        "category_id": 2,
        "author_ids": [4],
    },
    {
        "name": "Coraline",
        "price": 9.99,
        "image_url": "https://m.media-amazon.com/images/I/41W2XvvGyTL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": False,
        "description": "A dark fantasy novel for young readers by Neil Gaiman about a girl who finds an alternate world.",
        "detail_images": ['https://resizing.flixster.com/u4QgzhGunwGzwBKN6EfPWiRUUzI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2EyNjNmMjE2LWE5ZDEtNGI4Mi05ZjM1LTIzMWQxOWY2YTZiNC5qcGc='],
        "rating": 4,
        "product_stock": 28,
        "category_id": 2,
        "author_ids": [4],
    },
    {
        "name": "It",
        "price": 18.75,
        "image_url": "https://m.media-amazon.com/images/I/41VhN1LQRJL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": True,
        "description": "A horror novel by Stephen King about a group of friends who fight an evil entity.",
        "detail_images": ['https://m.media-amazon.com/images/I/71fAbpR9+RL._SY342_.jpg'],
        "rating": 5,
        "product_stock": 22,
        "category_id": 2,
        "author_ids": [1],
    },
    {
        "name": "The Stand",
        "price": 19.99,
        "image_url": "https://m.media-amazon.com/images/I/31ph4TtjzXL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": False,
        "description": "A post-apocalyptic dark fantasy novel by Stephen King.",
        "detail_images": ['https://m.media-amazon.com/images/I/51opD+my3wL._SX550_.jpg'],
        "rating": 5,
        "product_stock": 25,
        "category_id": 2,
        "author_ids": [1],
    },

    # Category: Romance (ID 3)
    {
        "name": "Verity",
        "price": 15.99,
        "image_url": "https://m.media-amazon.com/images/I/51gjPdeh3hL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": True,
        "description": "A thrilling and suspenseful romance novel by Colleen Hoover.",
        "detail_images": ['https://www.dtv.de/thumbnail/c1/71/78/1666346704/9783423230124__COVER_2D%20%28Produktcover%20Web%20klein%29_1920x1920.jpg'],
        "rating": 4,
        "product_stock": 30,
        "category_id": 3,
        "author_ids": [3],
    },
    {
        "name": "Ugly Love",
        "price": 10.99,
        "image_url": "https://m.media-amazon.com/images/I/41mBCtaJ1XL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": False,
        "description": "A touching and emotional romance novel by Colleen Hoover.",
        "detail_images": ['https://m.media-amazon.com/images/I/815wvjrMo-L._SY342_.jpg'],
        "rating": 4,
        "product_stock": 35,
        "category_id": 3,
        "author_ids": [3],
    },

    # Category: Poetry (ID 4)
    {
        "name": "Milk and Honey",
        "price": 14.99,
        "image_url": "https://m.media-amazon.com/images/I/41rrZplMctL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": True,
        "description": "A collection of poetry and prose about survival, love, and healing by Rupi Kaur.",
        "detail_images": ['https://m.media-amazon.com/images/I/61k1SMHqPhL._SY342_.jpg'],
        "rating": 5,
        "product_stock": 50,
        "category_id": 4,
        "author_ids": [5],
    },
    {
        "name": "The Sun and Her Flowers",
        "price": 13.99,
        "image_url": "https://m.media-amazon.com/images/I/41qnVPHflkL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": False,
        "description": "A second poetry collection about growth, healing, and honoring one's roots by Rupi Kaur.",
        "detail_images": ['https://m.media-amazon.com/images/I/41MwKJ2K7eL._SY342_.jpg'],
        "rating": 4,
        "product_stock": 45,
        "category_id": 4,
        "author_ids": [5],
    },

    # Category: Children's (ID 5)
    {
        "name": "Harry Potter and the Sorcerer's Stone",
        "price": 14.99,
        "image_url": "https://m.media-amazon.com/images/I/5152XTq24+L._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": True,
        "description": "The first book in the iconic Harry Potter series by J.K. Rowling.",
        "detail_images": ['https://treehousetoys.us/cdn/shop/products/web3.46.03PM_3f012ed1-d1d4-447e-a1b7-d2529bd9449e.jpg?v=1652130166&width=640'],
        "rating": 5,
        "product_stock": 30,
        "category_id": 5,
        "author_ids": [2],
    },
    {
        "name": "The Cat in the Hat",
        "price": 8.99,
        "image_url": "https://m.media-amazon.com/images/I/41j05R2RKJL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": True,
        "description": "A classic Dr. Seuss tale that introduces a whimsical cat who causes chaos.",
        "detail_images": ['https://m.media-amazon.com/images/I/61YjGI2JI4S._SX445_.jpg'],
        "rating": 5,
        "product_stock": 50,
        "category_id": 5,
        "author_ids": [8],
    },
    {
        "name": "Green Eggs and Ham",
        "price": 8.99,
        "image_url": "https://m.media-amazon.com/images/I/71e4ln93HOL._SY342_.jpg",
        "is_featured": False,
        "description": "A famous children's book by Dr. Seuss about a character who doesn't want to try a new food.",
        "detail_images": ['https://m.media-amazon.com/images/I/81yJzJ3KfIL._SX445_.jpg'],
        "rating": 5,
        "product_stock": 45,
        "category_id": 5,
        "author_ids": [8],
    },
    {
        "name": "Harry Potter and the Chamber of Secrets",
        "price": 15.99,
        "image_url": "https://m.media-amazon.com/images/I/51n-RPrkgSL._SY445_SX342_ControlCacheEqualizer_.jpg",
        "is_featured": False,
        "description": "The second installment of the Harry Potter series by J.K. Rowling.",
        "detail_images": ['https://static.wikia.nocookie.net/harrypotter/images/6/6d/Chamber_of_Secrets_New_UK_Cover.jpg/revision/latest?cb=20170109045927'],
        "rating": 5,
        "product_stock": 25,
        "category_id": 5,
        "author_ids": [2],
    },
]